
module.exports = Object.freeze({

    ADD_PRODUCT: 'ADD_PRODUCT',
    UPDATE_ON_TEXT_CHANGE: 'UPDATE_ON_TEXT_CHANGE',
    SET_IN_STOCK_ONLY_CHECKED: 'SET_IN_STOCK_ONLY_CHECKED',
    ADD_NEW_PRODUCT: 'ADD_NEW_PRODUCT',
    UPDATE_NEW_PRODUCT_NAME: 'UPDATE_NEW_PRODUCT_NAME',
    UPDATE_NEW_PRODUCT_PRICE: 'UPDATE_NEW_PRODUCT_PRICE',
    UPDATE_NEW_PRODUCT_CATEGORY: 'UPDATE_NEW_PRODUCT_CATEGORY',
    UPDATE_NEW_PRODUCT_IS_STOCKED: 'UPDATE_NEW_PRODUCT_IS_STOCKED',
    ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
    UPDATE_NEW_CATEGORY: 'UPDATE_NEW_CATEGORY',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    UPDATE_PRODUCT_IN_STOCK: 'UPDATE_PRODUCT_IN_STOCK',
});
